### ISSUE TITLE
Develop SC Media Interview and supporting brochure collateral

### ISSUE THREAD

**Issue by oliverrochford** [tenzir/events#1]
```[tasklist]
### Tasks
- [ ] Bio & Headshot Matthias
- [ ] Segment Title and Abstract
- [ ] Seed Questions
- [ ] Links and CTA's
```

**Comment by oliverrochford** [comment]
Interview will take place at:

BlackHat 2023 Interview
11:20am - 11:45am, Wednesday, August 9, 2023
Pacific Time - US & Canada
matthias.vallentin@tenzir.com, oliver.rochford@tenzir.com
A calendar invitation has been sent to your email address.

**Comment by oliverrochford** [comment]
We need to supply the following information and collateral by July 14th at the latest

Questionnaire: https://forms.monday.com/forms/91d1ba837f9061e24eaae323cb7f6b25?r=use1

**Headshot** Matthias
**Short Guest Bio** Matthias (1-2- paragraphs)


Segment Title (Max 80 Characters)
Segment Abstract: 2-3 Sentences
Seed Questions: Provide a list of seed questions that will be shared with the host/moderator in preparation for the interview.
Segment Resources: Please provide links you would like us to mention on the show or in the notes associated with your topic (Github, presentations, videos, blogs, articles or any other links to supporting information.)
Call To Action: If you have a special offer for our listeners on your landing page, please list your call to action here. If you do not enter a call to action, the host will read "For more information about [sponsor name] please visit: [landing page URL]"
Landing Page URL:  Please enter the URL that you would like us to direct listeners to during the segment. This should be easy to read aloud (i.e. [www.sponsorwebsite.com/rsac)](https://www.sponsorwebsite.com/rsac)) and the landing page should include any special offerings that you would like to entice our audience with.
Company Logo: A high resolution Vector, .PSD, or .AI formatted version of your company logo. Please submit a logo with light text, and a transparent background. This will be overlaid on a navy blue background for our lower-third graphics for the live stream
Guest Twitter Handle:
Company Twitter Handle:
Guest LI:
Company LI:
Guest Discord Handle:


WIP Document:
https://docs.google.com/document/d/1WhBrDAvsaDny_OyahbA9MMFoNBrfMXvzzNVl-aw6YpU/edit
